---
title: "R Notebook"
output: html_notebook
---

# Load libraries
```{r, warning = FALSE, message = FALSE}
library(knitr)
library(rmdformats)
library(ggplot2)
library(ggpubr)
library(GGally)
library(car)
library(tidyverse)
library(lme4)
library(lmerTest)
library("MuMIn")
library(lmtest)
library(boot)
library(modelsummary)
library(pandoc)
library(tinytable)
```

# Read dataset
```{r}
AllSubs_IndividualChoice <- read.csv('/Users/luisalvarez/Documents/GitHub/RM_Thesis_Neuroforecasting/ProcessedData/AllSubs_NeuralActivation_ISC.csv')

# Filter outliers. 
#AllSubs_IndividualChoice_C <- filter(AllSubs_IndividualChoice_C, Avg_peaks_pos_yes_cooks < 0.1)

```

# M1_C: Behavioral data
```{r, echo = FALSE}
M1 <- lmer(scale(W_score_scaled) ~ scale(Pos_arousal_scaled) + scale(Neg_arousal_scaled) + 
             (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)
#summary(M1_C)
#r.squaredGLMM(M1_C)
#confint(M1_C)
#AIC(M1_C)
```

# Neural ISC 
Note it appears that in the full model NAcc is being flipped by positive arousal and MPFC. 
```{r, echo = FALSE}
M2 <- lmer(scale(W_score_scaled) ~ 
               scale(NAcc_ISC) + 
               scale(AIns_ISC) + 
               scale(MPFC_ISC) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

M3<- lmer(scale(W_score_scaled) ~ 
               scale(Pos_arousal_scaled) + 
               scale(Neg_arousal_scaled) + 
               scale(NAcc_ISC) + 
               scale(AIns_ISC) + 
               scale(MPFC_ISC) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

ISC_list <- list(
  "Affect" = M1, 
  "Neuro ISC" = M2, 
  "Affect & Neuro ISC" = M3)

ISC_models <- modelsummary(ISC_list, stars=TRUE, statistic=NULL, output = "ISC_models.docx", gof_omit = "F|RMSE|Log|Num.Obs.|SD (Observations)") #%>% select(-part, -statistic)
ISC_models

```

```{r}
ggplot(AllSubs_IndividualChoice, aes(x = NAcc_ISC, y = (W_score_scaled), color=Type)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor() 
  #geom_text(aes(label = Trailer), vjust = 2)
```


# Neural sequence models
```{r, echo = FALSE}
M4 <- lmer(scale(W_score_scaled) ~ 
               scale(NAcc_onset) + 
               scale(AIns_middle) + 
               scale(MPFC_middle) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

M5 <- lmer(scale(W_score_scaled) ~ 
               scale(Pos_arousal_scaled) + 
               scale(Neg_arousal_scaled) + 
               scale(NAcc_onset) + 
               scale(AIns_middle) + 
               scale(MPFC_middle) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

Seq_list <- list(
  "Affect" = M1, 
  "Neuro seq" = M4, 
  "Affect & Neuro seq" = M5)

Seq_models <- modelsummary(Seq_list, stars=TRUE, statistic=NULL, output = "Seq_models.docx", gof_omit="F|RMSE|Log|Num.Obs.|SD (Observations)") #%>% select(-part, -statistic)
Seq_models
```

```{r}
ggplot(AllSubs_IndividualChoice, aes(x = NAcc_onset, y = (W_score_scaled), color=Type)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor() 
```
# Neural dem peaks
```{r, echo = FALSE}
M6 <- lmer(scale(W_score_scaled) ~ 
               scale(NAcc_dem_peak_pos) + 
               scale(AIns_dem_peak_pos) + 
               scale(MPFC_dem_peak_pos) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

M7 <- lmer(scale(W_score_scaled) ~ 
               scale(Pos_arousal_scaled) + 
               scale(Neg_arousal_scaled) + 
               scale(NAcc_dem_peak_pos) + 
               scale(AIns_dem_peak_pos) + 
               scale(MPFC_dem_peak_pos) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

Dem_peaks_list <- list(
  "Affect" = M1, 
  "Neuro dem peaks" = M6, 
  "Affect & Neuro dem peaks" = M7)

Dem_peaks_list <- modelsummary(Dem_peaks_list, stars=TRUE, statistic=NULL, output = "Dem_peaks.docx", gof_omit = "F|RMSE|Log|Num.Obs.|SD (Observations)") #%>% select(-part, -statistic)
Dem_peaks_list
```
# Neural dem peaks yes
```{r}
M8 <- lmer(scale(W_score_scaled) ~ 
               scale(NAcc_dem_peak_pos_yes) + 
               scale(AIns_dem_peak_pos_yes) + 
               scale(MPFC_dem_peak_pos_yes) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

M9 <- lmer(scale(W_score_scaled) ~ 
               scale(Pos_arousal_scaled) + 
               scale(Neg_arousal_scaled) + 
               scale(NAcc_dem_peak_pos_yes) + 
               scale(AIns_dem_peak_pos_yes) + 
               scale(MPFC_dem_peak_pos_yes) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

Dem_peaks_yes_list <- list(
  "Affect" = M1, 
  "Neuro dem peaks yes" = M8, 
  "Affect & Neuro dem peaks yes" = M9)

Dem_peaks_yes_list <- modelsummary(Dem_peaks_yes_list, stars=TRUE, statistic=NULL, output = "Dem_peaks_yes.docx", gof_omit = "F|RMSE|Log|Num.Obs.|SD (Observations)") #%>% select(-part, -statistic)
Dem_peaks_yes_list
```
Are NAcc_dem_peaks_pos_yes and MPFC_dem_peaks_pos_yes co-linear? 
```{r}
ggplot(AllSubs_IndividualChoice, aes(x = NAcc_dem_peak_pos_yes, y = (W_score_scaled), color=Type)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor() 
  # + geom_text(aes(label = Trailer), vjust = 2)
```

```{r}
M10 <- lmer(scale(W_score_scaled) ~ 
               scale(NAcc_avg_peak_pos) + 
               scale(AIns_avg_peak_pos) + 
               scale(MPFC_avg_peak_pos) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

M11 <- lmer(scale(W_score_scaled) ~ 
               scale(Pos_arousal_scaled) + 
               scale(Neg_arousal_scaled) + 
               scale(NAcc_avg_peak_pos) + 
               scale(AIns_avg_peak_pos) + 
               scale(MPFC_avg_peak_pos) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

Avg_peaks_yes_list <- list(
  "Affect" = M1, 
  "Neuro dem peaks yes" = M10, 
  "Affect & Neuro dem peaks yes" = M11)

Avg_peaks_yes_list <- modelsummary(Avg_peaks_yes_list, stars=TRUE, statistic=NULL, output = "Avg_peaks.docx", gof_omit = "F|RMSE|Log|Num.Obs.|SD (Observations)") #%>% select(-part, -statistic)
Avg_peaks_yes_list
```

```{r}
M12 <- lmer(scale(W_score_scaled) ~ 
               scale(NAcc_avg_peak_yes_pos) + 
               scale(AIns_avg_peak_yes_pos) + 
               scale(MPFC_avg_peak_yes_pos) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

M13 <- lmer(scale(W_score_scaled) ~ 
               scale(Pos_arousal_scaled) + 
               scale(Neg_arousal_scaled) + 
               scale(NAcc_avg_peak_yes_pos) + 
               scale(AIns_avg_peak_yes_pos) + 
               scale(MPFC_avg_peak_yes_pos) +
            (1|Participant) + (1|Trailer), data = AllSubs_IndividualChoice)

Avg_peaks_yes_list <- list(
  "Affect" = M1, 
  "Neuro avg peaks yes" = M12, 
  "Affect & Neuro dem peaks yes" = M13)

Avg_peaks_yes_list <- modelsummary(Avg_peaks_yes_list, stars=TRUE, statistic=NULL, output = "Avg_peaks_yes.docx", gof_omit = "F|RMSE|Log|Num.Obs.|SD (Observations)") #%>% select(-part, -statistic)
Avg_peaks_yes_list
```
```{r}
ggplot(AllSubs_IndividualChoice, aes(x = NAcc_avg_peak_yes_pos, y = (W_score_scaled), color=Type)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor() 
```




