---
title: "R Notebook"
output: html_notebook
---
# Load libraries
```{r}
library(knitr)
library(rmdformats)
library(ggplot2)
library(ggpubr)
library(GGally)
```


```{r, warning = FALSE, message = FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
library("MuMIn")
library(lmtest)
library(boot)
```
Read dataset
```{r}
AllSubs_NeuralActivation_H <- read.csv('/Users/luisalvarez/Documents/GitHub/RM_Thesis_Neuroforecasting/ProcessedData/AllSubs_NeuralActivation_Horror.csv')
```
# M1: Behavioral data
```{r, echo = FALSE}
M1 <- lmer(W_score~ scale(Pos_arousal) + scale(Neg_arousal) + 
             (1|Participant) + (1|Trailer), data = AllSubs_NeuralActivation_H)
summary(M1)
r.squaredGLMM(M1)
```

# M2: Neural activation (whole)
```{r, echo = FALSE}
M2 <- lmer(W_score~ scale(NAcc_whole) + scale(AIns_whole) + scale(MPFC_whole) +
            (1|Participant) + (1|Trailer), data = AllSubs_NeuralActivation_H)
summary(M2)
r.squaredGLMM(M2)
```

# M3: Neural activation (whole) + Behavioral data
```{r, echo = FALSE}
M3 <- lmer(W_score~ scale(Pos_arousal) + scale(Neg_arousal) +  
             scale(NAcc_whole) + scale(AIns_whole) + scale(MPFC_whole) + 
             (1|Participant) + (1|Trailer), data = AllSubs_NeuralActivation_H)
summary(M3)
r.squaredGLMM(M3)
```

# Compare brhavioral and neural models
```{r}
AIC(M1, M2, M3)
```

# M3 Pairs plot 
```{r}
W_score <- AllSubs_NeuralActivation_H %>% pull(W_score)
A_score <- AllSubs_NeuralActivation_H %>% pull(A_score)
F_score <- AllSubs_NeuralActivation_H %>% pull(F_score)

NAcc_whole <- AllSubs_NeuralActivation_H %>% pull(NAcc_whole)
AIns_whole <- AllSubs_NeuralActivation_H %>% pull(AIns_whole)
MPFC_whole <- AllSubs_NeuralActivation_H %>% pull(MPFC_whole)

M3_data <- data.frame(W_score, A_score, F_score, NAcc_whole, AIns_whole, MPFC_whole) 

ggpairs(M3_data)
```

# M4: Neural ISC 
```{r, echo = FALSE}
M4 <- lmer(W_score~ scale(NAcc_ISC) + scale(AIns_ISC) + scale(MPFC_ISC) +
             (1|Participant) + (1|Trailer), data = AllSubs_NeuralActivation_H)
summary(M4)
r.squaredGLMM(M4)
```

# M5: Neural ISC + Behavioral data
```{r, echo = FALSE}
M5 <- lmer(W_score~ scale(Pos_arousal) + scale(Neg_arousal) + 
             scale(NAcc_ISC) + scale(AIns_ISC) + scale(MPFC_ISC) +
             scale(Pos_arousal):scale(NAcc_ISC) + scale(Pos_arousal):scale(AIns_ISC) + scale(Pos_arousal):scale(MPFC_ISC) + scale(Neg_arousal):scale(NAcc_ISC) + scale(Neg_arousal):scale(AIns_ISC) + scale(Neg_arousal):scale(MPFC_ISC) + 
             (1|Participant) + (1|Trailer), data = AllSubs_NeuralActivation_H)
summary(M5)
r.squaredGLMM(M5)
```

# M6: Neural activation (middle)
```{r, echo = FALSE}
M6 <- lmer(W_score~ scale(NAcc_middle) + scale(AIns_middle) + scale(MPFC_middle) +
            (1|Participant) + (1|Trailer), data = AllSubs_NeuralActivation_H)
summary(M6)
r.squaredGLMM(M6)
```

# M7: Neural activation (middle) + behavioral data
```{r, echo = FALSE}
M7 <- lmer(W_score~ scale(Pos_arousal) + scale(Neg_arousal) +  
             scale(NAcc_middle) + scale(AIns_middle) + scale(MPFC_middle) +
             (1|Participant) + (1|Trailer), data = AllSubs_NeuralActivation_H)
summary(M7)
r.squaredGLMM(M7)
```