---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load libraries
```{r}
library(knitr)
library(rmdformats)
library(ggplot2)
library(ggpubr)
library(GGally)
library(car)
library(tidyverse)
library(lme4)
library(lmerTest)
library("MuMIn")
library(lmtest)
library(boot)
library(modelsummary)
library(pandoc)
library(tinytable)
```

# Read dataset
```{r}
# Read filtered data.
#AllSubs_NeuralActivation <- read.csv('/Users/luisalvarez/Documents/GitHub/RM_Thesis_Neuroforecasting/ProcessedData/AllSubs_NeuralActivation_Aggregate_Combined_Comedy_clean.csv')

AllSubs_NeuralActivation_raw <- read.csv('/Users/luisalvarez/Documents/GitHub/RM_Thesis_Neuroforecasting/ProcessedData/AllSubs_NeuralActivation_ISC.csv')

trailer_cols = c('rc1', 'rc10', 'rc11', 'rc12', 'rc2', 'rc3', 'rc4', 'rc5', 'rc6', 'rc7', 'rc8',
                 'rc9', 'uc1', 'uc2', 'uc3', 'uc4')

# Read aggregate metrics. 
Aggregate_data <- read.csv('/Users/luisalvarez/Documents/SpanLab/Aggregate_metrics_labeled_updated.csv') %>%
                          filter(label==trailer_cols)

# Get the avg neural signals. 
col_means = c("Trailer", "Pos_arousal_scaled", "Neg_arousal_scaled", "W_score_scaled", 'NAcc_onset', 'AIns_onset', 'MPFC_onset',
        'NAcc_middle', 'AIns_middle', 'MPFC_middle', 'NAcc_offset', 'AIns_offset', 'MPFC_offset', 'NAcc_whole',
        'AIns_whole', 'MPFC_whole', 'NAcc_ISC', 'AIns_ISC', 'MPFC_ISC', "NAcc_dem_peak_pos", "AIns_dem_peak_pos",
        "MPFC_dem_peak_pos", "NAcc_dem_peak_neg", "AIns_dem_peak_neg", "MPFC_dem_peak_neg", "NAcc_dem_peak_pos_yes",
        "AIns_dem_peak_pos_yes", "MPFC_dem_peak_pos_yes", "NAcc_dem_peak_pos_no" , "AIns_dem_peak_pos_no",
        "MPFC_dem_peak_pos_no", 'Affect_cooks', 'Whole_cooks', 'Onset_cooks', 'Middle_cooks', 'Offset_cooks',
        'ISC_cooks', 'Ind_peaks_pos_cooks', 'Ind_peaks_neg_cooks', 'Dem_peaks_pos_cooks', 'Dem_peaks_neg_cooks')

AllSubs_NeuralActivation_filtered <- filter(AllSubs_NeuralActivation_raw, Type=="Comedy", 
                                Dem_peaks_pos_cooks < 0.20) %>%
                                select(col_means) %>%
                                group_by(Trailer) %>%
                                summarise_all(list(mean))

# Add aggregate columns. 


```


```{r}
ggplot(AllSubs_NeuralActivation, aes(x=NAcc_dem_peak_pos , y=(GoT_M1))) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor()
```



# Create data frames for each model.
```{r}
# Define aggregate variables. 
GoT_W1 <- rank(log(AllSubs_NeuralActivation$Gross_US_W1_num / AllSubs_NeuralActivation$Theaters_US_W1_num))
GoT_M1 <- rank(log(AllSubs_NeuralActivation$Gross_US_M1 / AllSubs_NeuralActivation$Theaters_US_M1))
GoT_total <- rank(log(AllSubs_NeuralActivation$Gross_Total_US / AllSubs_NeuralActivation$Total_Theaters_US))

All_Gross_W1_log <- log(AllSubs_NeuralActivation$Gross_US_W1_num)
All_Theaters_W1 <- AllSubs_NeuralActivation$Theaters_US_W1_num

All_Gross_M1_log <- rank(log(AllSubs_NeuralActivation$Gross_US_M1))
All_Theaters_M1 <- AllSubs_NeuralActivation$Theaters_US_M1

# Define affect variables.
All_PA <- AllSubs_NeuralActivation$Pos_arousal_scaled
All_NA <- AllSubs_NeuralActivation$Neg_arousal_scaled

FW_US_M1_df <- data.frame(All_Gross_W1_log, All_Theaters_W1) 
FM_US_M14_df <- data.frame(All_Gross_M1_log, All_Theaters_M1) 
```
# Neural signals.  
```{r}
# Define ISC variables. 
All_NAcc_ISC <- AllSubs_NeuralActivation$NAcc_ISC
All_AIns_ISC <- AllSubs_NeuralActivation$AIns_ISC
All_MPFC_ISC <- AllSubs_NeuralActivation$MPFC_ISC

All_NAcc_whole <- AllSubs_NeuralActivation$NAcc_whole
All_AIns_whole <- AllSubs_NeuralActivation$AIns_whole
All_MPFC_whole <- AllSubs_NeuralActivation$MPFC_whole

All_NAcc_onset <- AllSubs_NeuralActivation$NAcc_onset
All_AIns_onset <- AllSubs_NeuralActivation$AIns_onset
All_MPFC_onset <- AllSubs_NeuralActivation$MPFC_onset

All_NAcc_middle <- AllSubs_NeuralActivation$NAcc_middle
All_AIns_middle <- AllSubs_NeuralActivation$AIns_middle
All_MPFC_middle <- AllSubs_NeuralActivation$MPFC_middle

All_NAcc_offset <- AllSubs_NeuralActivation$NAcc_offset
All_AIns_offset <- AllSubs_NeuralActivation$AIns_offset
All_MPFC_offset <- AllSubs_NeuralActivation$MPFC_offset

All_NAcc_ind_peak_pos <- AllSubs_NeuralActivation$NAcc_ind_peaks_pos
All_AIns_ind_peak_pos <- AllSubs_NeuralActivation$AIns_ind_peaks_pos
All_MPFC_ind_peak_pos <- AllSubs_NeuralActivation$MPFC_ind_peaks_pos

All_NAcc_ind_peak_neg <- AllSubs_NeuralActivation$NAcc_ind_peaks_neg
All_AIns_ind_peak_neg <- AllSubs_NeuralActivation$AIns_ind_peaks_neg
All_MPFC_ind_peak_neg <- AllSubs_NeuralActivation$MPFC_ind_peaks_neg

All_NAcc_tr_peak_pos <- AllSubs_NeuralActivation$NAcc_trailer_peak_pos
All_AIns_tr_peak_pos <- AllSubs_NeuralActivation$AIns_trailer_peak_pos
All_MPFC_tr_peak_pos <- AllSubs_NeuralActivation$MPFC_trailer_peak_pos

All_NAcc_tr_peak_neg <- AllSubs_NeuralActivation$NAcc_trailer_peak_neg
All_AIns_tr_peak_neg <- AllSubs_NeuralActivation$AIns_trailer_peak_neg
All_MPFC_tr_peak_neg <- AllSubs_NeuralActivation$MPFC_trailer_peak_neg
```
# Plot correlation between budget and number of theaters (M1).
```{r}
ggplot(AllSubs_NeuralActivation, aes(x = Budget, y = (All_Theaters_M1))) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor()
```

# Neuroforecasting: First month.
```{r, echo = FALSE}

# M1: Aggregate data 
FMG_US_M1 <- lm(All_Gross_M1_log ~ scale(All_Theaters_M1)
              + scale(IMDb_rating)
            , data = AllSubs_NeuralActivation)

# M2: Affect data 
FMG_US_M2 <- lm(All_Gross_M1_log ~ 
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
            , data = AllSubs_NeuralActivation)

# Define models while controlling number of theaters (GT).
# M4: Aggregate data
FMGT_M3 <- lm((GoT_M1) ~ 
         + scale(IMDb_rating)
            , data = AllSubs_NeuralActivation )

# M15: affect model.
FMGT_M4 <- lm((GoT_M1) ~ 
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
            , data = AllSubs_NeuralActivation )

```

## Sequence neural signals.
```{r}
# M5: Sequence neural signals.
FMG_US_M5 <- lm((All_Gross_M1_log) ~ 
         + scale(NAcc_onset) 
         + scale(AIns_middle)
         + scale(MPFC_middle)
            , data = AllSubs_NeuralActivation )

# M6: Full model = Aggregate + affect + neural.
FMG_US_M6 <- lm((All_Gross_M1_log) ~ 
         + scale(All_Theaters_M1)
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_onset) 
         + scale(AIns_middle)
         + scale(MPFC_middle)
            , data = AllSubs_NeuralActivation)

# M7: Neural sequence.
FMGT_M7 <- lm((GoT_M1) ~ 
         + scale(NAcc_onset) 
         + scale(AIns_middle)
         + scale(MPFC_middle)
            , data = AllSubs_NeuralActivation )

# # M8: Full model: affect + neural sequence.
FMGT_M8 <- lm((GoT_M1) ~ 
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_onset) 
         + scale(AIns_middle)
         + scale(MPFC_middle)
            , data = AllSubs_NeuralActivation )

Log_seq_list = list(
  "Aggregate_G" = FMG_US_M1, 
  "Affect_G" = FMG_US_M2, 
  "Neuro_G" = FMG_US_M5,
  "Full_G" = FMG_US_M6, 
  "Aggregate_GT" = FMGT_M3,
  "Affect_GT" = FMGT_M4, 
  "Neuro_GT" = FMGT_M7,
  "Full_GT" = FMGT_M8)

Log_seq_models <- modelsummary(Log_seq_list, stars=TRUE, statistic=NULL, output = "dataframe", gof_omit = "F|RMSE|Log") %>% select(-part, -statistic)
    #|>
    #group_tt(j = list("Gross (GT)" = 2:5, "Gross/Theaters (GT)" = 6:9))
Log_seq_models
```
```{r}
ggplot(AllSubs_NeuralActivation, aes(x=NAcc_dem_peak_pos , y=(GoT_M1))) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_cor()
```


## ISC neural signals.
```{r}
# G: Neuro ISC
FM_US_M9 <- lm((All_Gross_M1_log) ~ 
         + scale(NAcc_ISC) 
         + scale(AIns_ISC)
         + scale(MPFC_ISC)
            , data = AllSubs_NeuralActivation )

# G: Full model: theaters + affect + neural ISC
FM_US_M10 <- lm((All_Gross_M1_log) ~ 
         + scale(All_Theaters_M1)
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_ISC) 
         + scale(AIns_ISC)
         + scale(MPFC_ISC)
            , data = AllSubs_NeuralActivation )

# GT: Neural ISC
FMGT_M11 <- lm((GoT_M1) ~ 
         + scale(NAcc_ISC) 
         + scale(AIns_ISC)
         + scale(MPFC_ISC)
            , data = AllSubs_NeuralActivation )

# # GT: Full model: affect + neural ISC
FMGT_M12 <- lm((GoT_M1) ~ 
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_ISC) 
         + scale(AIns_ISC)
         + scale(MPFC_ISC)
            , data = AllSubs_NeuralActivation )

Log_isc_list = list(
  "Aggregate_G" = FMG_US_M1, 
  "Affect_G" = FMG_US_M2, 
  "Neuro_G" = FM_US_M9,
  "Full_G" = FM_US_M10, 
  "Aggregate_GT" = FMGT_M3,
  "Affect_GT" = FMGT_M4, 
  "Neuro_GT" = FMGT_M11,
  "Full_GT" = FMGT_M12)

Log_isc_models <- modelsummary(Log_isc_list, stars=TRUE, statistic=NULL, output = "dataframe", gof_omit = "F|RMSE|Log") %>% select(-part, -statistic)
Log_isc_models
```

## Neural Individual Positive Peaks.
```{r}
# G: Neural positive peaks (individual).
FM_US_M13 <- lm((All_Gross_M1_log) ~ 
         + scale(NAcc_ind_peaks_pos) 
         + scale(AIns_ind_peaks_pos)
         + scale(MPFC_ind_peaks_pos)
            , data = AllSubs_NeuralActivation )

# G: Full model: theaters + affect + neural ind positive peaks.
FM_US_M14 <- lm((All_Gross_M1_log) ~ 
         + scale(All_Theaters_M1)
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_ind_peaks_pos) 
         + scale(AIns_ind_peaks_pos)
         + scale(MPFC_ind_peaks_pos)
            , data = AllSubs_NeuralActivation )

# GT: Neural Ind Pos Peak
FMGT_M15 <- lm((GoT_M1) ~ 
         + scale(NAcc_ind_peaks_pos) 
         + scale(AIns_ind_peaks_pos)
         + scale(MPFC_ind_peaks_pos)
            , data = AllSubs_NeuralActivation )

# # GT: Full model: affect + neural ind pos peak
FMGT_M16 <- lm((GoT_M1) ~ 
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_ind_peaks_pos) 
         + scale(AIns_ind_peaks_pos)
         + scale(MPFC_ind_peaks_pos)
            , data = AllSubs_NeuralActivation )

Log_ind_pos_peak_list = list(
  "Aggregate_G" = FMG_US_M1, 
  "Affect_G" = FMG_US_M2, 
  "Neuro_G" = FM_US_M13,
  "Full_G" = FM_US_M14, 
  "Aggregate_GT" = FMGT_M3,
  "Affect_GT" = FMGT_M4, 
  "Neuro_GT" = FMGT_M15,
  "Full_GT" = FMGT_M16)

Log_ind_pos_peak_models <- modelsummary(Log_ind_pos_peak_list, stars=TRUE, statistic=NULL, output = "dataframe", gof_omit = "F|RMSE|Log") %>% select(-part, -statistic)
Log_ind_pos_peak_models
```
## Neural Individual Negative Peaks.
```{r}
FM_US_M17 <- lm((All_Gross_M1_log) ~ 
         + scale(NAcc_ind_peaks_neg) 
         + scale(AIns_ind_peaks_neg)
         + scale(MPFC_ind_peaks_neg)
            , data = AllSubs_NeuralActivation)

# M10: Full model: theaters + affect + neural ind negative peaks.
FM_US_M18 <- lm((All_Gross_M1_log) ~ 
         + scale(All_Theaters_M1)
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_ind_peaks_neg) 
         + scale(AIns_ind_peaks_neg)
         + scale(MPFC_ind_peaks_neg)
            , data = AllSubs_NeuralActivation)

# GT: Neural Ind Pos Peak
FMGT_M19 <- lm((GoT_M1) ~ 
         + scale(NAcc_ind_peaks_neg) 
         + scale(AIns_ind_peaks_neg)
         + scale(MPFC_ind_peaks_neg)
            , data = AllSubs_NeuralActivation )

# # GT: Full model: affect + neural ind pos peak
FMGT_M20 <- lm((GoT_M1) ~ 
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_ind_peaks_neg) 
         + scale(AIns_ind_peaks_neg)
         + scale(MPFC_ind_peaks_neg)
            , data = AllSubs_NeuralActivation )

Log_ind_neg_peak_list = list(
  "Aggregate_G" = FMG_US_M1, 
  "Affect_G" = FMG_US_M2, 
  "Neuro_G" = FM_US_M17,
  "Full_G" = FM_US_M18, 
  "Aggregate_GT" = FMGT_M3,
  "Affect_GT" = FMGT_M4, 
  "Neuro_GT" = FMGT_M19,
  "Full_GT" = FMGT_M20)

Log_ind_neg_peak_models <- modelsummary(Log_ind_neg_peak_list, stars=TRUE, statistic=NULL, output = "dataframe", gof_omit = "F|RMSE|Log") %>% select(-part, -statistic)
Log_ind_neg_peak_models
```

## Neural Trailer Positive Peaks.
```{r}
# G: Neural positive peaks (trailer).
FM_US_M21 <- lm((All_Gross_M1_log) ~ 
         + scale(NAcc_dem_peak_pos_yes) 
         + scale(AIns_dem_peak_pos_yes)
         + scale(MPFC_dem_peak_pos_yes)
            , data = AllSubs_NeuralActivation )

# G: Full model: theaters + affect + neural trailer positive peaks.
FM_US_M22 <- lm((All_Gross_M1_log) ~ 
         + scale(All_Theaters_M1)
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_dem_peak_pos_yes) 
         + scale(AIns_dem_peak_pos_yes)
         + scale(MPFC_dem_peak_pos_yes)
            , data = AllSubs_NeuralActivation)

# GT: Neural Ind Pos Peak
FMGT_M23 <- lm((GoT_M1) ~ 
         + scale(NAcc_dem_peak_pos_yes) 
         + scale(AIns_dem_peak_pos_yes)
         + scale(MPFC_dem_peak_pos_yes)
            , data = AllSubs_NeuralActivation )

# # GT: Full model: affect + neural ind pos peak
FMGT_M24 <- lm((GoT_M1) ~ 
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_dem_peak_pos_yes) 
         + scale(AIns_dem_peak_pos_yes)
         + scale(MPFC_dem_peak_pos_yes)
            , data = AllSubs_NeuralActivation )

Log_tra_pos_peak_list = list(
  "Aggregate_G" = FMG_US_M1, 
  "Affect_G" = FMG_US_M2, 
  "Neuro_G" = FM_US_M21,
  "Full_G" = FM_US_M22, 
  "Aggregate_GT" = FMGT_M3,
  "Affect_GT" = FMGT_M4, 
  "Neuro_GT" = FMGT_M23,
  "Full_GT" = FMGT_M24)

Log_tra_pos_peak_models <- modelsummary(Log_tra_pos_peak_list, stars=TRUE, statistic=NULL, output = "dataframe", gof_omit = "F|RMSE|Log") %>% select(-part, -statistic)
Log_tra_pos_peak_models
```

## Neural Trailer Negative Peaks.
```{r}
# G: Neural negative peaks (trailer).
FM_US_M25 <- lm((All_Gross_M1_log) ~ 
         + scale(NAcc_trailer_peak_neg) 
         + scale(AIns_trailer_peak_neg)
         + scale(MPFC_trailer_peak_neg)
            , data = AllSubs_NeuralActivation )

# G: Full model: theaters + affect + neural trailer negative peaks.
FM_US_M26 <- lm((All_Gross_M1_log) ~ 
         + scale(All_Theaters_M1)
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_trailer_peak_neg) 
         + scale(AIns_trailer_peak_neg)
         + scale(MPFC_trailer_peak_neg)
            , data = AllSubs_NeuralActivation)

# GT: Neural Tra Neg Peak
FMGT_M27 <- lm((GoT_M1) ~ 
         + scale(NAcc_trailer_peak_neg) 
         + scale(AIns_trailer_peak_neg)
         + scale(MPFC_trailer_peak_neg)
            , data = AllSubs_NeuralActivation )

# # GT: Full model: affect + neural tra neg peak
FMGT_M28 <- lm((GoT_M1) ~ 
         + scale(IMDb_rating)
         + scale(Pos_arousal_scaled) 
         + scale(Neg_arousal_scaled)
         + scale(NAcc_trailer_peak_neg) 
         + scale(AIns_trailer_peak_neg)
         + scale(MPFC_trailer_peak_neg)
            , data = AllSubs_NeuralActivation )

Log_tra_neg_peak_list = list(
  "Aggregate_G" = FMG_US_M1, 
  "Affect_G" = FMG_US_M2, 
  "Neuro_G" = FM_US_M25,
  "Full_G" = FM_US_M26, 
  "Aggregate_GT" = FMGT_M3,
  "Affect_GT" = FMGT_M4, 
  "Neuro_GT" = FMGT_M27,
  "Full_GT" = FMGT_M28)

Log_tra_neg_peak_models <- modelsummary(Log_tra_neg_peak_list, stars=TRUE, statistic=NULL, output = "dataframe", gof_omit = "F|RMSE|Log") %>% select(-part, -statistic)
Log_tra_neg_peak_models
```


